version: "3.8"

services:
  db:
    build:
      context: ./db
      dockerfile: Dockerfile
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    volumes:
      - db-data:/var/lib/postgresql/data:delegated
  redis:
    image: "redis"
    ports:
      - "6379:6379"
    expose:
      - 6379
volumes:
  db-data: